# Generated by Django 2.0.1 on 2018-07-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(upload_to='')),
                ('species', models.CharField(choices=[('PUSS', 'Cat'), ('DOGGO', 'Dog')], default='PUSS', max_length=16)),
                ('elo_rating', models.IntegerField(default=1000)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='PetSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('elo_rating', models.IntegerField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet')),
            ],
            options={
                'db_table': 'pet_snapshots',
            },
        ),
    ]
