# Generated by Django 2.0.1 on 2018-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20180721_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('PUSS', 'Cat'), ('DOGGO', 'Dog')], default='PUSS', max_length=16),
        ),
    ]
