# Generated by Django 2.0.1 on 2018-08-19 08:25

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20180722_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Anonymous', max_length=256),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(default='Anonymous', max_length=256),
        ),
        migrations.AlterField(
            model_name='pet',
            name='mediafile',
            field=models.FileField(upload_to=pets.models.Pet.create_filename),
        ),
    ]
