# Generated by Django 2.0.1 on 2018-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20180819_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsnapshot',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
