# Generated by Django 2.0.1 on 2018-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petsnapshot_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
