# Generated by Django 2.0.1 on 2018-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['disabled', 'verified']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Misc', 'Misc')], default='Cat', max_length=16),
        ),
    ]
